name: gps_transporte
description: App de transporte para La Paz

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Mapa y utilidades geoespaciales
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  # GeolocalizaciÃ³n (paquete usado en la app)
  geolocator: ^14.0.2

  # Cliente HTTP para peticiones a APIs
  http: ^1.1.0
  
  # JSON serialization
  json_annotation: ^4.8.1
  
  # Almacenamiento local
  shared_preferences: ^2.2.0
  
  # WebSocket para tracking en tiempo real
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - punt.json  # Vincula el JSON
